### ISSUE TITLE
xcrun referenced, though xcrun isn't available on Linux.

### ISSUE THREAD

**Issue by awesomebing1** [darwin-on-arm/xnu#30]
I have Ubuntu 15.04, and I'm trying to build xnu following the wiki's instructions.

I've shortened the faulty command to `make TARGET_CONFIGS="debug arm armpba8" NO_DTRACE_SYMS=YES`.

I get the following output while running make: https://ghostbin.com/paste/u9okp

I do know that xcrun is only available with Xcode, and I can't install Xcode in Linux.

**Comment by musisat** [comment]
I think installing the Darwin SDK is what puts xcrun in your usr/bin folder. This at least works on Ubuntu 14.04. If you have followed all of the instructions, it could be a problem with Ubuntu 15.04.

**Comment by awesomebing1** [comment]
Aha, thank you. Looking at the error log, dpkg-buildpackage couldn't find all of the needed dependencies.  I can edit those into the wiki page. However, it does error out with yet another error, so I'll open another issue in a bit.

Thank you!
