### ISSUE TITLE
Can't boot with u-boot on Raspberry Pi 3 (arm64)

### ISSUE THREAD

**Issue by ghost** [darwin-on-arm/xnu#44]
I compiled XNU and U-BOOT for raspberry pi 3,
but when I run the command >fatload mmc 0 0x84000000 /uImage
he say:
> reading /uImage
>"Synchronous Abort" handler, esr 0x96000045
>ERL: 3b370440
>LR: 3Bb370440
>x0: 0000000056190527 x1: 0000000000000020
>x2: 000000003b370928 x3: 000000003b370a68
>x4: 000000003af488f0 x5: 000000000000000d
>x6: ....
>Resetting CPU

And when I run this command 
>fatload mmc 0 0x0000800 /uImage 

with 
>setenv 

and 
> bootm 

he said:
>"## Booting kernel from Legacy Image at 00000800 ..."
>      Image Name: GenericBooter
>      Image Type: ARM Linux Kernel Image (uncompressed)
>      Data Size: 35087584 Bytes = 33,5 MiB
>      Load address: 00008000
>      Entry Point: 00008000
>      Verifying Checksum ... OK
>      Loading Kernel Image ... OK
>Starting Kernel ...
And he said : 
>"Synchronous Abort" handler, esr 0x02000000
>ERL: 8004
>LR: 3B34edf0
>x0: 0000000000000000 x1: 0000000000000000
>x2: 0000000000000000 x3: 0000000000000000
>x4: 0000000000000000 x5: 0000000000000000
>x6: .....
>Resetting CPU
>Resetting ....
Anyone can help me please ?

**Comment by HuErr** [comment]
Hi, is the problem solved?

**Comment by ghost** [comment]
nop :/

**Comment by danielwangksu** [comment]
same here any one have idea about this error?

**Comment by winocm** [comment]
These projects are long deprecated.
